#!/usr/bin/env bash
# tests/lint/test_no_hardcoded_service_lists.sh — REG-08 STRICT lint gate.
#
# Forbid hand-edited service lists outside the generated artifact + codegen script.
# As of Phase 12, templates/services/registry.yaml is single source of truth;
# every catalog block lives in registry.yaml and lib/_registry.indexed.sh
# (generated by scripts/codegen/registry-to-indexed.sh). Any new
# `declare -A SERVICE_GROUPS=(...)` etc. anywhere else = regression.
#
# STRICT mode (different from Phase 10 baseline lint):
#   Phase 10 ENV-05 grandfathers existing callsites (Phase 14 migrates).
#   Phase 12 IS the migration phase — registry.yaml is the new source of truth.
#   Hand-edited lists outside the allowlist are NEVER legal after Phase 12 ships.
#
# Allowlist:
#   lib/_registry.indexed.sh              — generated artifact (IS the projection)
#   scripts/codegen/registry-to-indexed.sh — codegen (emits patterns as strings)
#
# Forbidden patterns (8):
#   1. declare -A SERVICE_GROUPS=
#   2. declare -A NAME_TO_VERSION_KEY=
#   3. declare -A NAME_TO_SERVICES=
#   4. declare -A NAMED_PROFILE_EXPANSION=
#   5. declare -A NAMED_PROFILE_DESC=
#   6. declare -A NAMED_PROFILE_IMPLIED=
#   7. ^[[:space:]]*ALL_COMPOSE_PROFILES=    (scalar, line-anchored)
#   8. ^[[:space:]]*SERVICE_GROUP_ORDER=     (scalar, line-anchored)
#
# Pattern anchoring: ^[[:space:]]* skips comment lines (starting with '#').
#
# Exit: 0 = no hand-edited lists outside allowlist; N>0 = forbidden match count.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "$REPO_ROOT" || exit 1

echo "## test_no_hardcoded_service_lists"

# Allowlist — files where the patterns are LEGAL by design.
# lib/_registry.indexed.sh     IS the generated projection (contains all patterns legitimately).
# scripts/codegen/registry-to-indexed.sh   emits patterns as Python string literals.
ALLOWLIST=(
    "lib/_registry.indexed.sh"
    "scripts/codegen/registry-to-indexed.sh"
)

# Combined declare -A pattern: matches any of the 6 known assoc-array symbols.
DECLARE_PATTERN='^[[:space:]]*declare -A (SERVICE_GROUPS|NAME_TO_VERSION_KEY|NAME_TO_SERVICES|NAMED_PROFILE_EXPANSION|NAMED_PROFILE_DESC|NAMED_PROFILE_IMPLIED)='

# Scalar patterns: each must start the line (optional leading whitespace only).
SCALAR_PATTERNS=(
    '^[[:space:]]*ALL_COMPOSE_PROFILES='
    '^[[:space:]]*SERVICE_GROUP_ORDER='
)

fail_count=0

_is_allowlisted() {
    local file="$1"
    local allow
    for allow in "${ALLOWLIST[@]}"; do
        if [[ "$file" == "$allow" ]]; then
            return 0
        fi
    done
    return 1
}

_scan_pattern() {
    local pat="$1"
    # grep -rnE returns lines in format "file:lineno:text". Filter through allowlist.
    local file lineno rest
    while IFS=: read -r file lineno rest; do
        [[ -z "$file" ]] && continue
        if _is_allowlisted "$file"; then
            continue
        fi
        echo "  FAIL: $file:$lineno — hand-edited service list: $rest"
        fail_count=$((fail_count + 1))
    done < <(grep -rnE "$pat" --include='*.sh' lib/ scripts/ install.sh 2>/dev/null || true)
}

_scan_pattern "$DECLARE_PATTERN"
for pat in "${SCALAR_PATTERNS[@]}"; do
    _scan_pattern "$pat"
done

echo ""
if [[ "$fail_count" -eq 0 ]]; then
    echo "  PASS: no hand-edited service lists found outside allowlist"
    echo "## test_no_hardcoded_service_lists: PASS"
    exit 0
fi

echo "## test_no_hardcoded_service_lists: FAIL ($fail_count forbidden match(es))"
echo "  Source of truth is templates/services/registry.yaml."
echo "  Edit registry.yaml then run \`make registry-codegen\`. See docs/adr/0012-*."
exit "$fail_count"
